Updated `useDrag`'s `preventScroll` to take in a time duration for the delay
pmndrs/use-gesture pull request #308
Opened 2021-05-26 10:37 UTC by ajaypillay

I've updated the `preventScroll` argument for the `useDrag` handler to accept a duration in `ms` to act as the "long press" before dragging is initiated. If set to true, this defaults to `250ms`. Updated the docs to reflect this as well.

PS: This is my first PR :-)

2021-05-28 05:56 UTC, dbismut requested changes

2021-05-28 05:56 UTC, dbismut commented on packages/core/src/config/dragConfigResolver.ts
> +  preventScroll(value: number | boolean = 0, _k: string, { preventScrollAxis = 'x' }) {
Should be `preventScrollAxis = 'y'`?

2021-05-28 05:56 UTC, dbismut commented on documentation/pages/docs/options.mdx
> +<Specs types={['boolean', 'number']}defaultValue="0" />
`defaultValue="false"` will be clearer IMO, and leads to the same behavior.

2021-05-28 05:56 UTC, dbismut commented on packages/core/src/config/dragConfigResolver.ts
> +    }
I think you could simplify this to, it's more readable IMO:

```js
if (!SUPPORT.touch) return 0
if (typeof value === "number") return value
return value ? DEFAULT_PREVENT_SCROLL_DELAY : 0
```

2021-05-28 05:56 UTC, dbismut commented on packages/core/src/engines/DragEngine.ts
> +        if (state.axis === (config.preventScrollAxis || 'x')) {
I don't think you need `|| 'x'` since `config.preventScrollAxis` should be defaulted to `x`, unless I'm missing something?

2021-05-28 06:02 UTC, dbismut commented
Hi @ajaypillay thanks for this! I've requested some changes.

Also, unfortunately, the CI doesn't run for branches which origin isn't `main` so I'll have to run tests manually for now, and they fail.

Try running:

```bash
# check types
yarn tsc
# run tests
yarn test
```

Tests are pretty easy to fix (essentially in `config.test.ts` you need to modify the object matching the config to match your PR changes).

I'm going to comment on types on how to fix them (happens in `dragConfigResolver.ts`).

2021-05-28 06:08 UTC, dbismut commented on packages/core/src/config/dragConfigResolver.ts
> +    if (preventScrollAxis) this.preventScrollAxis = preventScrollAxis
TypeScript should complain here as `this` is not defined. In the function arguments, pass `this` as in:

```ts
preventScroll(this: InternalDragOptions, value: number | boolean = 0, _k: string, { preventScrollAxis = 'x' })
//            ^^^^
```
You'll also need to type the config passed as the third argument as `preventScrollAxis` will be typed as a string and not `x` | `y`. Bottom line:

```ts
  preventScroll(
    this: InternalDragOptions,
    value: number | boolean = 0,
    _k: string,
    { preventScrollAxis = 'x' }: DragConfig
//                               ^^^^^^^^^^
  )
```

2021-05-28 08:55 UTC, ajaypillay commented
> Tests are pretty easy to fix (essentially in `config.test.ts` you need to modify the object matching the config to match your PR changes).

Thanks for taking the time to comment the changes. Unfortunately I don't have much experience with TypeScript and wasn't entirely sure on how to run the tests on my own. I've run `yarn tsc` and `yarn test`, but they both throw the error that they cannot find the module `@use-gesture/core` or its corresponding type declarations (I've done `npm install` already too just in case) for various files.

I've tried running `yarn tsc` and `yarn test` in both the root directory and in `/test` but it's the same outcome, don't think that made a difference.

What am I missing here?

2021-05-28 10:08 UTC, dbismut commented
Ok, sorry, the setup is not trivial. First, delete all node_modules and lock files generated by npm in all pacakges. Install `pnpm` by running `npm install -g pnpm`.

Then run `pnpm install`. After that, you should be able to run `pnpm test` and `pnpm tsc` (in that case you can replace `pnpm` with `npm` or `yarn`).

You can also run `pnpm docs:start` and `pnpm demo:dev` to spawn the documentation and sandboxes.

Let me know if this helps!

2021-05-28 21:48 UTC, ajaypillay commented
No worries. After running `npm install -g pnpm`, I got the error `pnpm: command not found`. Turns out that I had to be root in order to install it successfully.

I fixed all that is necessary and all tests have passed.
![image](https://user-images.githubusercontent.com/917752/120044681-e0fc4080-c040-11eb-8ca2-06bba058b857.png)

But `pnpm tsc` fails.
![image](https://user-images.githubusercontent.com/917752/120044728-f96c5b00-c040-11eb-9dcd-f4677c644759.png)

I didn't touch any of the 49 files with errors (all in `packages/vanilla/src` and `packages/react/src`), so I'm not quite sure why this is being thrown. The file they are all trying to import from is `use-gesture-core.cjs`:
![image](https://user-images.githubusercontent.com/917752/120044893-56681100-c041-11eb-8e99-925cf207433c.png)

How should I go about remedying this?

2021-05-29 06:36 UTC, dbismut commented
Can you try running `pnpm dev` and try again?

2021-05-29 09:33 UTC, ajaypillay commented
Yep, it says the project is valid and it successfully created the links. `pnpm test` still works, all passed, but `pnpm tsc` throws the same errors.

2021-05-29 17:03 UTC, dbismut commented
It is weird that you have any `package-lock.json` files at all. `pnpm` should only generate `pnpm-lock.yaml` files. You shouldn't use `npm` at all here...

Also, I think `preventScrollAxis` should default to `y` but also accept `xy` as an option in case you'd want to prevent scrolling on all axis.

2021-05-29 22:26 UTC, ajaypillay commented
I think I might not have deleted those `package-lock.json` files originally. My original `npm install` seems to have messed things up.

I cloned my fork again and made the necessary changes. `pnpm test` and `pnpm tsc` both have passed.

I have also made the change to allow for `xy` to be a valid option. I have tested it on my local devices and it seems to be working fine.

I appreciate the time taken to explain the necessary steps and the code feedback. I definitely learned something along the way as I am primarily familiar with JavaScript but not so much TypeScript, or much testing for that matter. Thank you.

Let me know if there's anything else!

2021-05-29 22:27 UTC, ajaypillay commented
Also - I'm not sure why I merged something else instead of my new commits, so I've opened up a new PR with it and I'm going to close this one. I can't seem to undo that merge.

2021-05-29 22:50 UTC, closed without merging