Added option to configure keyboard displacement in the drag gesture
pmndrs/use-gesture pull request #577
Opened 2023-01-15 01:18 UTC by markjaniczak

PR for issue #576.

In hindsight, maybe it's better to initialise and store the delta map only when the config changes?

2023-01-17 10:27 UTC, dbismut requested changes

2023-01-18 00:05 UTC, markjaniczak commented on packages/core/src/engines/DragEngine.ts
> +    const keysDeltaMap = getKeysDeltaMap(this.config.keyboardDisplacement)
What do you think of the latest change here?

2023-01-23 14:13 UTC, markjaniczak commented
Are there other changes required to merge this?

2023-01-24 12:43 UTC, dbismut commented
Sorry, I've been kept busy. Looks good to me! Just run the changeset command and set the change request as patch with a description and we're good to go!

2023-01-28 09:29 UTC, dbismut approved these changes

2023-01-28 09:29 UTC, merged